version: "3"

services:
  # web:
  #   container_name: "${WEB_NAME}"
  #   image: nginx:latest
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx:/etc/nginx

  app:
    # very important to keep the container running.
    tty: true
    container_name: "${APP_NAME}"
    build:  
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/var/www/html/app

  db:
    tty: true
    image: mysql:latest
    container_name: "${DB_NAME}"
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    # volumes:
    #   - ./db:/var/lib/mysql



# networks:
#   application:
#     driver: bridge
